### ISSUE TITLE
Adding a screenshot to README.md file 

### ISSUE THREAD

**Issue by gvanuxem** [pbroadbery/aldor-idea-plugin#48]
An easy way would be to open an issue, say 'Screenshot', cut & paste a .png screenshot in the description filler, use the code in the issue filler to add it to the README.md file and close the issue. For GUI things it's  always informative I think.

**Comment by pbroadbery** [comment]
Hi Greg,

You're quite right - I'll add a couple.  Any objections if I use the
screenshot you sent?

Thanks,

Peter

**Comment by gvanuxem** [comment]
Hello Peter,

The one I sent is VisualStudio Code, a project I'm working on :-)

The screenshot showed my adaptation of some parts of your flex file (mostly
the ideas, what needs to be colorizing, and your categorization). The
colorization scheme was already functional but that allowed me to greatly
enhance it.

https://github.com/gvanuxem/fricas-vscode

It's, as its base, an editor, not an IDE. With fast start up, thing that
I'm looking for.

Greg

**Comment by pbroadbery** [comment]
OK - I've added another screenshot.
There will be an aldor one to match soon, but need to make a bit of progress on some features.

**Comment by gvanuxem** [comment]
Great! And I like a lot the navigation via symbols or even the
documentation access. Will look deeper in it.
